### ISSUE TITLE
Negative time delta in first couple of frames for Mania Replays

### ISSUE THREAD

**Issue by sinanates17** [kszlim/osu-replay-parser#39]
After executing the following code:

```
from osrparse import Replay
replay = Replay.from_path("strong.osr")
with open("replay.txt", "w") as f:
    for frame in replay.replay_data:
        f.write(str(frame) + "\n")
```

The first few lines of replay.txt are as follows.  It also appears that Key 9 is considered to have been pressed during those first 2 frames while no keys were actually pressed at the very beginning of this play before any notes came down.

```
ReplayEventMania(time_delta=0, keys=<KeyMania.K9: 256>)
ReplayEventMania(time_delta=12158, keys=<KeyMania.K9: 256>)
ReplayEventMania(time_delta=-12158, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=0, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=12, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=17, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=13, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=20, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=18, keys=<KeyMania: 0>)
```

In addition, it seems that very occasionally, there is a `time_delta` that is exceedingly large. Lines 68-71 in replay.txt is as follows:

```
ReplayEventMania(time_delta=18, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=11193, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=0, keys=<KeyMania: 0>)
ReplayEventMania(time_delta=6, keys=<KeyMania: 0>)
```

I'm unsure if there's a meaning behind the negative `time_delta`s. I'm trying to loop through all the frames in a replay and assign a timestamp to each frame using the `time_delta`s. Due to these negatives, I'm not exactly sure which frame corresponds to the first actual frame of the replay.

Here is the exact replay I used in this code: https://cdn.discordapp.com/attachments/571707842235727902/1101982751344828436/strong.osr

And here is the replay.txt file I generated: 
[replay.txt](https://github.com/kszlim/osu-replay-parser/files/11360106/replay.txt)

This is a replay for the following beatmap: https://osu.ppy.sh/beatmapsets/1657903#mania/3384013

The occurrence of negative frame deltas in the first few ReplayEvents seemed to be pretty consistent across different replays and different maps. I wasn't able to replicate the random, large `time_delta` in the middle of the replay, however.

**Comment by tybug** [comment]
There's two distinct comments here. The easier one to comment on is the negative and/or large time_deltas. This is not a bug, as these frames are present as-is in the lzma data. Negative time frames do have special meaning, and depending on your use case you can treat them in different ways. Lazer [skips negative time frames](https://github.com/ppy/osu/blob/1587d4b26fbad691242544a62dbf017a78705ae3/osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs#L247-L250). circlecore incorporates negative frames in [a different way](https://github.com/circleguard/circlecore/blob/f92cc30af53f9b8666e629fdf9fb571a9bee941a/circleguard/loadables.py#L767-L796), which may even be more correct than lazer. I can't offer advice beyond that.

The second comment is about the first two frames of the replay having an odd keys value. This is due to osrs containing two frames at the beginning with an x value of 265, which is interpreted by mania as K9. Lazer [removes these frames](https://github.com/ppy/osu/blob/6a04708a7e9801949c6c7ac7ddf6a4d7fa0835e5/osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs#L290-L294). I would argue we should do the same - these frames are (relatively) harmless for std, but cause issues for minigames, which e.g. interpret the x value as keys (mania).

Doing so is a breaking change and requires a major version bump.

**Comment by sinanates17** [comment]
I see, thank you for clarifying everything. I seem to have found my way around proper timestamps as well!

**Comment by tybug** [comment]
We now remove these two frames in [v7.0.0](https://github.com/kszlim/osu-replay-parser/releases/tag/v7.0.0).
